# Generated by Django 5.1.5 on 2025-01-27 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='launchsite',
            old_name='location',
            new_name='coordinates',
        ),
        migrations.RemoveField(
            model_name='lunarmission',
            name='landing_date',
        ),
        migrations.RemoveField(
            model_name='lunarmission',
            name='landing_site',
        ),
        migrations.RemoveField(
            model_name='lunarmission',
            name='launch_date',
        ),
        migrations.RemoveField(
            model_name='lunarmission',
            name='launch_site',
        ),
        migrations.CreateModel(
            name='LandingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landing_date', models.DateTimeField()),
                ('landing_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.landingsite')),
            ],
        ),
        migrations.AddField(
            model_name='lunarmission',
            name='landing_details',
            field=models.OneToOneField(default=123, on_delete=django.db.models.deletion.CASCADE, to='polls.landingdetails'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LaunchDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launch_date', models.DateTimeField()),
                ('launch_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.launchsite')),
            ],
        ),
        migrations.AddField(
            model_name='lunarmission',
            name='launch_details',
            field=models.OneToOneField(default=123, on_delete=django.db.models.deletion.CASCADE, to='polls.launchdetails'),
            preserve_default=False,
        ),
    ]
