# Generated by Django 5.1.5 on 2025-01-27 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_location_launchsite_coordinates_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('crew_capacity', models.IntegerField()),
                ('crew', models.ManyToManyField(to='polls.crewmember')),
                ('landing_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.landingdetails')),
                ('launch_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.launchdetails')),
            ],
        ),
    ]
